trigger:
  - master

pool:
  vmImage: windows-latest

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.0.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - task: DotNetCoreCLI@2
    name: "Build"
    inputs:
      command: 'build'
      projects: '**/ICS_Project.sln'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**/*Tests*.csproj'